[project]
name = "tsim-demos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bloqade-circuit>=0.11.0",
    "bloqade-tsim>=0.1.0",
    "ipykernel>=7.1.0",
]
